#
# Copyright (c) 2015 University of Cambridge
# All rights reserved.
#
#
#  File:
#        output_port_lookup_regs_defines.tcl
#
#  Description:
#        This file is automatically generated with tcl defines for the software
#
# This software was developed by
# Stanford University and the University of Cambridge Computer Laboratory
# under National Science Foundation under Grant No. CNS-0855268,
# the University of Cambridge Computer Laboratory under EPSRC INTERNET Project EP/H040536/1 and
# by the University of Cambridge Computer Laboratory under DARPA/AFRL contract FA8750-11-C-0249 ("MRC2"), 
# as part of the DARPA MRC research programme.
#
# @NETFPGA_LICENSE_HEADER_START@
#
# Licensed to NetFPGA C.I.C. (NetFPGA) under one or more contributor
# license agreements.  See the NOTICE file distributed with this work for
# additional information regarding copyright ownership.  NetFPGA licenses this
# file to you under the NetFPGA Hardware-Software License, Version 1.0 (the
# "License"); you may not use this file except in compliance with the
# License.  You may obtain a copy of the License at:
#
#   http://www.netfpga-cic.org
#
# Unless required by applicable law or agreed to in writing, Work distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations under the License.
#
# @NETFPGA_LICENSE_HEADER_END@
#

set OUTPUT_PORT_LOOKUP_REGS_ID_0_OFFSET 0x0
set OUTPUT_PORT_LOOKUP_REGS_ID_0_DEFAULT 0x0001DA02
set OUTPUT_PORT_LOOKUP_REGS_ID_0_WIDTH 32
set OUTPUT_PORT_LOOKUP_REGS_VERSION_0_OFFSET 0x4
set OUTPUT_PORT_LOOKUP_REGS_VERSION_0_DEFAULT 0x1
set OUTPUT_PORT_LOOKUP_REGS_VERSION_0_WIDTH 32
set OUTPUT_PORT_LOOKUP_REGS_RESET_0_OFFSET 0x8
set OUTPUT_PORT_LOOKUP_REGS_RESET_0_DEFAULT 0x0
set OUTPUT_PORT_LOOKUP_REGS_RESET_0_WIDTH 16
set OUTPUT_PORT_LOOKUP_REGS_FLIP_0_OFFSET 0xC
set OUTPUT_PORT_LOOKUP_REGS_FLIP_0_DEFAULT 0x0
set OUTPUT_PORT_LOOKUP_REGS_FLIP_0_WIDTH 32
set OUTPUT_PORT_LOOKUP_REGS_DEBUG_0_OFFSET 0x10
set OUTPUT_PORT_LOOKUP_REGS_DEBUG_0_DEFAULT 0x0
set OUTPUT_PORT_LOOKUP_REGS_DEBUG_0_WIDTH 32
set OUTPUT_PORT_LOOKUP_REGS_PKTIN_0_OFFSET 0x14
set OUTPUT_PORT_LOOKUP_REGS_PKTIN_0_DEFAULT 0x0
set OUTPUT_PORT_LOOKUP_REGS_PKTIN_0_WIDTH 32
set OUTPUT_PORT_LOOKUP_REGS_PKTOUT_0_OFFSET 0x18
set OUTPUT_PORT_LOOKUP_REGS_PKTOUT_0_DEFAULT 0x0
set OUTPUT_PORT_LOOKUP_REGS_PKTOUT_0_WIDTH 32
set OUTPUT_PORT_LOOKUP_REGS_LUTHIT_0_OFFSET 0x1C
set OUTPUT_PORT_LOOKUP_REGS_LUTHIT_0_DEFAULT 0x0
set OUTPUT_PORT_LOOKUP_REGS_LUTHIT_0_WIDTH 32
set OUTPUT_PORT_LOOKUP_REGS_LUTMISS_0_OFFSET 0x20
set OUTPUT_PORT_LOOKUP_REGS_LUTMISS_0_DEFAULT 0x0
set OUTPUT_PORT_LOOKUP_REGS_LUTMISS_0_WIDTH 32
